# fly.toml app configuration file generated for joltword on 2023-07-24T16:52:17-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "joltword"
primary_region = "bos"

[env]
  DATABASE_URL = "file:/data/sqlite.db"
  PORT = "3000"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
